# -*- coding: utf-8 -*-
"""Data Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSJCqzWrktBDX30dA4el0dYbTGPmoaUO

**Importing libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
# %matplotlib inline

"""**Importing Data**"""

Names = ['Kim', 'Jerry', 'Tim', 'Mary', 'James', 'Tom', 'Keith', 'Sara', 'Raymond', 'Dennis', 'Larry', 'Bony', 'Beatrice', 'John', 'Harry', 'Bianca', 'Marshal', 'Mandy', 'David', 'Edward', 'Robert', 'Michael', 'Elaina', 'Cathy', 'Caroline', 'Samantha', 'Vicky', 'Clara', 'Richard'
, 'Stephen']
Weight = [40, 45, 47, 48, 49, 49, 54, 55, 56, 56, 57, 59, 63, 65, 67, 67, 69, 72, 75, 77, 79, 80, 80, 80, 81, 82, 85, 87, 88, 90]

"""**Creating *Dataframe* and storing it in a variable.**"""

d1 = pd.DataFrame({"Names": Names, 'Weight': Weight})

"""**Checking Dataframe by calling the variable**"""

d1

"""**Calcuating the mean**"""

d1['Weight'].mean (skipna = True)

"""**Calculating the median**"""

d1['Weight'].median (skipna = True)

"""**Calcuating the mode**



"""

d1.mode (axis = 0, dropna = True, numeric_only = True)

"""Calcuating the Range """

d1['Weight'].min(), d1['Weight'].max()

"""Interquartile range"""

def iqr(x):
  return np.subtract(*np.percentile(x, [75, 25]))

d1[['Weight']].apply(iqr)

"""Variance"""

d1['Weight'].var (skipna = True)

"""Standard Deviation"""

d1['Weight'].std (skipna = True)